version: "3"
services:
  mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nodeserver
      MYSQL_PASSWORD: jayvishaal
      MYSQL_DATABASE: invente
    ports:
      - "3306:3306"
    volumes:
      - mysqlstore:/var/lib/mysql
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass jay_vishaal_j_144
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  phpmyadmin:
    image: "phpmyadmin:apache"
    restart: always
    depends_on:
      - mysql
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
  nodejs:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
      # - graylog
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: nodeserver
      MYSQL_PASS: jayvishaal
      MYSQL_DB: invente
    depends_on:
      - mysql
      - redis
      # - graylog
  # # MongoDB: https://hub.docker.com/_/mongo/
  # mongodb:
  #   image: mongo:3
  # # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=localhost
  #     - network.host=0.0.0.0
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g
  # # Graylog: https://hub.docker.com/r/graylog/graylog/
  # graylog:
  #   image: graylog/graylog:3.3
  #   environment:
  #     # CHANGE ME (must be at least 16 characters)!
  #     - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
  #     # Password: admin
  #     - GRAYLOG_ROOT_PASSWORD_SHA2=ac7ce0d3c9c4d0efc70ee093c4441bbc19f1165c8c723a28f376266c54267652
  #     - GRAYLOG_HTTP_EXTERNAL_URI=https://log.jayvishaalj.cf/
  #   links:
  #     - mongodb:mongo
  #     - elasticsearch
  #   depends_on:
  #     - mongodb
  #     - elasticsearch
  #   ports:
  #     # Graylog web interface and REST API
  #     - "9000:9000"
  #     # Syslog TCP
  #     - "1514:1514"
  #     # Syslog UDP
  #     - "1514:1514/udp"
  #     # GELF TCP
  #     - "12201:12201"
  #     # GELF UDP
  #     - "12201:12201/udp"

volumes:
  mysqlstore:
